In [1]:
# finding key connectors

In [2]:
users = [
 { "id": 0, "name": "Hero" },
 { "id": 1, "name": "Dunn" },
 { "id": 2, "name": "Sue" },
 { "id": 3, "name": "Chi" },
 { "id": 4, "name": "Thor" },
 { "id": 5, "name": "Clive" },
 { "id": 6, "name": "Hicks" },
 { "id": 7, "name": "Devin" },
 { "id": 8, "name": "Kate" },
 { "id": 9, "name": "Klein" }
]

In [3]:
friendships = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4),
 (4, 5), (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)]

# For example, the tuple (0, 1) indicates that the data scientist with id 0 (Hero) and
# the data scientist with id 1 (Dunn) are friends. 

In [4]:
# For example, we might want to add a list of friends to each user. First we set each
# user’s friends property to an empty list:

for user in users:
    user["friends"] = []

In [5]:
# And then we populate the lists using the friendships data:

for i, j in friendships :
        users[i]["friends"].append(users[j])
        users[j]["friends"].append(users[i])
    

In [6]:
for user in users:
    print(user["friends"])

[{'id': 1, 'name': 'Dunn', 'friends': [{'id': 0, 'name': 'Hero', 'friends': [...]}, {'id': 2, 'name': 'Sue', 'friends': [{'id': 0, 'name': 'Hero', 'friends': [...]}, {...}, {'id': 3, 'name': 'Chi', 'friends': [{...}, {...}, {'id': 4, 'name': 'Thor', 'friends': [{...}, {'id': 5, 'name': 'Clive', 'friends': [{...}, {'id': 6, 'name': 'Hicks', 'friends': [{...}, {'id': 8, 'name': 'Kate', 'friends': [{...}, {'id': 7, 'name': 'Devin', 'friends': [{...}, {...}]}, {'id': 9, 'name': 'Klein', 'friends': [{...}]}]}]}, {'id': 7, 'name': 'Devin', 'friends': [{...}, {'id': 8, 'name': 'Kate', 'friends': [{'id': 6, 'name': 'Hicks', 'friends': [{...}, {...}]}, {...}, {'id': 9, 'name': 'Klein', 'friends': [{...}]}]}]}]}]}]}]}, {'id': 3, 'name': 'Chi', 'friends': [{...}, {'id': 2, 'name': 'Sue', 'friends': [{'id': 0, 'name': 'Hero', 'friends': [...]}, {...}, {...}]}, {'id': 4, 'name': 'Thor', 'friends': [{...}, {'id': 5, 'name': 'Clive', 'friends': [{...}, {'id': 6, 'name': 'Hicks', 'friends': [{...}, {'

In [33]:
for user in users:
    print(user['friends'][0]['friends'])

[{'id': 0, 'name': 'Hero', 'friends': [{'id': 1, 'name': 'Dunn', 'friends': [...]}, {'id': 2, 'name': 'Sue', 'friends': [{...}, {'id': 1, 'name': 'Dunn', 'friends': [...]}, {'id': 3, 'name': 'Chi', 'friends': [{'id': 1, 'name': 'Dunn', 'friends': [...]}, {...}, {'id': 4, 'name': 'Thor', 'friends': [{...}, {'id': 5, 'name': 'Clive', 'friends': [{...}, {'id': 6, 'name': 'Hicks', 'friends': [{...}, {'id': 8, 'name': 'Kate', 'friends': [{...}, {'id': 7, 'name': 'Devin', 'friends': [{...}, {...}]}, {'id': 9, 'name': 'Klein', 'friends': [{...}]}]}]}, {'id': 7, 'name': 'Devin', 'friends': [{...}, {'id': 8, 'name': 'Kate', 'friends': [{'id': 6, 'name': 'Hicks', 'friends': [{...}, {...}]}, {...}, {'id': 9, 'name': 'Klein', 'friends': [{...}]}]}]}]}]}]}]}]}, {'id': 2, 'name': 'Sue', 'friends': [{'id': 0, 'name': 'Hero', 'friends': [{'id': 1, 'name': 'Dunn', 'friends': [...]}, {...}]}, {'id': 1, 'name': 'Dunn', 'friends': [...]}, {'id': 3, 'name': 'Chi', 'friends': [{'id': 1, 'name': 'Dunn', 'fri

In [7]:
# First we find the total number of connections, by summing up the lengths of all the
# friends lists:

def numberOfFriends(user) :
    return len(user["friends"])

totalConnection = sum(numberOfFriends(user) for user in users)

for user in users:
    print(numberOfFriends(user))

2
3
3
3
2
3
2
2
3
1


In [8]:
num_users = len(users) 
avg_connections = totalConnection/num_users

print(avg_connections)



2.4


In [9]:
num_of_friends_by_id = [(user["id"], numberOfFriends(user)) for user in users]

print(num_of_friends_by_id)

[(0, 2), (1, 3), (2, 3), (3, 3), (4, 2), (5, 3), (6, 2), (7, 2), (8, 3), (9, 1)]


In [10]:
sorted(num_of_friends_by_id, key=lambda x: x[1], reverse=True)


[(1, 3),
 (2, 3),
 (3, 3),
 (5, 3),
 (8, 3),
 (0, 2),
 (4, 2),
 (6, 2),
 (7, 2),
 (9, 1)]

In [11]:
def friends_of_friend_ids_bad(user):
 # "foaf" is short for "friend of a friend"
 return [foaf["id"]
 for friend in user["friends"] # for each of user's friends
 for foaf in friend["friends"]] # get each of _their_ friends

print(friends_of_friend_ids_bad(users[3]))

[0, 2, 3, 0, 1, 3, 3, 5]


In [12]:
print([friend["id"] for friend in users[0]["friends"]])
print( [friend["id"] for friend in users[1]["friends"]])
print([friend["id"] for friend in users[2]["friends"]])

[1, 2]
[0, 2, 3]
[0, 1, 3]


In [13]:
# go over this again

def not_the_same(user, other_user):
    """two users are not the same if they have different ids"""
    return user["id"] != other_user["id"]

In [14]:
"go overr this again"

def not_friends(user, other_user):
    return all(not_the_same(friend, other_user) for friend in user["friends"])

In [15]:
print(not_friends(users[0], users[8]))

True


In [16]:
from collections import Counter

def friends_of_friends_ids(user):
    return Counter((foaf["id"]) for friends in user["friends"] for foaf in friends["friends"]
                   if not_the_same(user, foaf) and not_friends(user, foaf)
    )

In [17]:
print(friends_of_friends_ids(users[0]))

Counter({3: 2})


In [18]:
interests = [
 (0, "Hadoop"), (0, "Big Data"), (0, "HBase"), (0, "Java"),
 (0, "Spark"), (0, "Storm"), (0, "Cassandra"),
 (1, "NoSQL"), (1, "MongoDB"), (1, "Cassandra"), (1, "HBase"),
 (1, "Postgres"), (2, "Python"), (2, "scikit-learn"), (2, "scipy"),
 (2, "numpy"), (2, "statsmodels"), (2, "pandas"), (3, "R"), (3, "Python"),
 (3, "statistics"), (3, "regression"), (3, "probability"),
 (4, "machine learning"), (4, "regression"), (4, "decision trees"),
 (4, "libsvm"), (5, "Python"), (5, "R"), (5, "Java"), (5, "C++"),
 (5, "Haskell"), (5, "programming languages"), (6, "statistics"),
 (6, "probability"), (6, "mathematics"), (6, "theory"),
 (7, "machine learning"), (7, "scikit-learn"), (7, "Mahout"),
 (7, "neural networks"), (8, "neural networks"), (8, "deep learning"),
 (8, "Big Data"), (8, "artificial intelligence"), (9, "Hadoop"),
 (9, "Java"), (9, "MapReduce"), (9, "Big Data")
]

In [19]:
from sklearn.linear_model import LinearRegression
import numpy as np
from matplotlib.pylab import subplot



In [20]:
X = np.arange(10)

print(X)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
Y = X+np.random.rand(10)

print(Y)

[0.52311403 1.72124224 2.67513069 3.43792849 4.18406462 5.27001947
 6.83466067 7.46947899 8.52467024 9.57883475]


In [22]:
lr = LinearRegression()

In [23]:
X,Y = X.reshape((-1,1)), Y.reshape((-1,1))

print(X)
print(Y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0.52311403]
 [1.72124224]
 [2.67513069]
 [3.43792849]
 [4.18406462]
 [5.27001947]
 [6.83466067]
 [7.46947899]
 [8.52467024]
 [9.57883475]]


In [24]:
lr.fit(X, Y)

LinearRegression()

In [25]:
lr.coef_

array([[0.99620227]])

In [26]:
lr.score(X,Y)

0.9957376392572788

In [27]:
xi = np.linspace(0,10,15)
print(xi)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [28]:
xi = xi.reshape(-1,1)
print(xi)

[[ 0.        ]
 [ 0.71428571]
 [ 1.42857143]
 [ 2.14285714]
 [ 2.85714286]
 [ 3.57142857]
 [ 4.28571429]
 [ 5.        ]
 [ 5.71428571]
 [ 6.42857143]
 [ 7.14285714]
 [ 7.85714286]
 [ 8.57142857]
 [ 9.28571429]
 [10.        ]]


In [29]:
yp= lr.predict(xi)
print(yp)

[[ 0.53900419]
 [ 1.25057724]
 [ 1.96215029]
 [ 2.67372334]
 [ 3.3852964 ]
 [ 4.09686945]
 [ 4.8084425 ]
 [ 5.52001556]
 [ 6.23158861]
 [ 6.94316166]
 [ 7.65473472]
 [ 8.36630777]
 [ 9.07788082]
 [ 9.78945388]
 [10.50102693]]
